In [2]:
import numpy as np



1. 创建数组
1.1 使用ones,empty,zero生成数组

In [3]:
np.ones(shape=[2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.zeros(shape=[2,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
np.empty(shape=[3,4])

array([[6.90745567e-310, 4.86061387e-316, 0.00000000e+000,
        0.00000000e+000],
       [2.22809558e-312, 5.93416138e-038, 6.48678806e+169,
        4.05313834e+174],
       [6.59451932e-066, 2.00493655e-076, 1.95248304e+160,
        4.09071250e-037]])

1.2 使用linspace,arange生成数组


In [12]:
np.linspace(0,100,8) # 左闭右闭，步长
#np.arange(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [13]:
np.arange(0,100,8)

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96])

1.3 生成某种函数分布的数组

In [15]:
# 均匀分布
#np.random.uniform(-1,1,100)
#正态分布
np.random.normal(-1,1,100)

array([-0.63318046, -1.55466061, -2.9831026 , -2.19968573, -1.1851955 ,
        0.16829577, -1.53466117, -0.6438978 , -3.51011324, -0.57333915,
       -1.71915415,  0.37828815, -1.15530444, -0.85862673, -1.12455346,
       -0.18530622,  0.1905044 ,  1.43425224, -4.17458293,  0.11319654,
       -1.2970849 , -1.95063573, -0.92437131, -1.48885255, -0.65603931,
       -2.16566819, -2.95373397,  0.8350116 ,  0.43486954, -0.85815183,
       -0.57946631,  0.26969565, -0.05040913, -0.27645352, -0.16702733,
       -2.97642419, -1.38758044, -1.41197695, -2.05152255, -1.16654277,
       -1.55208541, -0.86345294, -0.64728338, -0.93770549,  1.23415722,
        1.70391159, -0.09908855, -1.34830432,  0.04302596, -1.71996759,
        0.53078303, -1.54559557, -0.84192598, -0.73114383, -0.93600166,
       -1.75482767, -2.85485987, -1.50527858, -0.652396  , -0.11136764,
       -1.59183403, -1.24203602, -0.68897746,  0.11659021, -1.32494604,
       -2.05301582, -0.04692128, -1.15551604, -1.60568858, -0.81

2.索引
一维数组
arr[]
二维数组
arr[][]

3.类型转换
3.1 numpy&&tersor类型转换
3.2  numpy&&list转换

In [23]:
import numpy as np
import torch
arr=np.empty(shape=[3,4])
print(arr)
torch_arr=torch.from_numpy(arr)
print(torch_arr)
arr1=torch_arr.numpy()
print(arr1)

[[6.90745567e-310 4.86061387e-316 0.00000000e+000 0.00000000e+000]
 [2.22809558e-312 5.93416138e-038 6.48678806e+169 4.05313834e+174]
 [6.59451932e-066 2.00493655e-076 1.95248304e+160 4.09071250e-037]]
tensor([[6.9075e-310, 4.8606e-316,  0.0000e+00,  0.0000e+00],
        [2.2281e-312,  5.9342e-38, 6.4868e+169, 4.0531e+174],
        [ 6.5945e-66,  2.0049e-76, 1.9525e+160,  4.0907e-37]],
       dtype=torch.float64)
[[6.90745567e-310 4.86061387e-316 0.00000000e+000 0.00000000e+000]
 [2.22809558e-312 5.93416138e-038 6.48678806e+169 4.05313834e+174]
 [6.59451932e-066 2.00493655e-076 1.95248304e+160 4.09071250e-037]]


In [25]:
list1=[[1,2],[3,5],[4,7]]
print(list1)
arr1=np.array(list1)
print(arr1)
list2=arr1.tolist()
print(list2)

[[1, 2], [3, 5], [4, 7]]
[[1 2]
 [3 5]
 [4 7]]
[[1, 2], [3, 5], [4, 7]]


4.维度变换

In [31]:
data1=np.random.normal(0,1 ,size=(2,3))
print(data1)
data1.reshape((3,2))

[[ 0.16941484 -1.7731076   0.564812  ]
 [-1.92499514 -1.45349825  0.18814635]]


array([[ 0.16941484, -1.7731076 ],
       [ 0.564812  , -1.92499514],
       [-1.45349825,  0.18814635]])